INSERT INTO menu_items (restaurant_id, name, cost, image_url, description, is_vegan, is_vegetarian, is_gluten_free)
VALUES (1, 'Shrimp Tempura (8pcs)', 999, 'https://simplyhomecooked.com/wp-content/uploads/2019/12/shrimp-tempura-recipe-8.jpg', 'This dish is made with fresh shrimp dipped in tempura batter and deep-fried until perfectly crispy. Served with soy sauce or tempura dipping sauce.', false, false, false),
(1, 'Vegetable Tempura (8pcs)', 799, 'https://static01.nyt.com/images/2013/10/23/dining/23JPFLEX1/23JPFLEX1-articleLarge.jpg', 'Dipped in batter and deep-fried, each vegetable gets cooked perfectly on the inside, while the natural sweetness and flavor is enhanced. You would enjoy them piping hot with a delicate dipping sauce with grated daikon.', true, true, false),
(1, 'Sashimi Combo (16pcs)', 1899, 'https://images.immediate.co.uk/production/volatile/sites/2/2015/05/8756.jpg?quality=90&resize=768%2C574', 'Assorted fresh sashimi with rice. A colourful assortment of thinly sliced seafood. Four pieces of salmon sashimi, four pieces of tuna sashimi, four pieces of sockeye salmon sashimi, and four 4 pieces of red snapper sashimi.', false, false, true),
(1, 'Chicken Teriyaki Dinner', 1499, 'https://www.cookingclassy.com/wp-content/uploads/2018/04/teriyaki-chicken-15.jpg', 'Crispy skinless chicken thighs stir-fried and swimming in a beautiful flavoured teriyaki sauce. A hint of garlic adds a twist on a traditional Japanese Teriyaki Chicken.', false, false, false),
(2, 'Gluten Free Japanese Curry', 1499, 'https://assets.bonappetit.com/photos/610d630e2f1b400ec4217042/1:1/w_2240,c_limit/0921-curry-vegetables.jpg', 'Japanese curry is a popular dish both in and outside of Japan. It is relatively much sweeter than other types of asian curry. The secret ingredient here is the special curry roux.', true, true, true),
(2, 'Salmon Teriyaki Dinner', 1599, 'https://i1.wp.com/chefsavvy.com/wp-content/uploads/teriyaki-salmon.jpg', 'Grilled salmon fillets and vegetable with teriyaki sauce and rice. Covered with a amazing teriyaki sauce and finished off with sesame seeds, a declicious healthy dinner.', false, false, false),
(2, 'Beef Teriyaki Dinner', 1599, 'https://therecipecritic.com/wp-content/uploads/2016/09/super-easy-beef-teriyaki.jpg', 'Marinated thinly sliced beef and vegetables with teriyaki sauce. Meat is grilled with a highly flavoured glaze of soy sauce and sake. Served over fried rice or noodles.', false, false, false),
(3, 'Yosenabe', 1399, 'https://www.thelastfoodblog.com/wp-content/uploads/2021/01/teriyaki-tofu-l_s.jpg', 'Yosenabe is a basic Japanese hot pot where you can cook ingredients of your choice — chicken, seafood, tofu, and all kinds of vegetables — in a delicious dashi-based broth.', false, false, true)
(3, 'Plant Based Sashimi', 1499, 'https://assets.epicurious.com/photos/555cf321644d45515b759070/master/w_1280,c_limit/51221630_sashimi-salad-with-soy-orange_6x4.jpg', 'Super-healthy and really light, this beautiful salad is bright-looking and -tasting. This is a new wow-worthy veggie-made product that is unbelievably similar to the regular sashimi!', true, true, true)
(3, 'Miso Soup', 599, 'https://www.crowdedkitchen.com/wp-content/uploads/2020/03/Vegan-miso-soup-5-1.jpg', 'Our Miso soup has a deep savory flavor, with toasty, funky, and salty-sweet richness. It is not only delicious but also full of probiotics, which contribute to improved gut health', false, true, true)
(3, 'Vegetarian Japanese Curry', 1099, 'https://v1.nitrocdn.com/KQYMGOLIdXGmoAcyJsPOrQDKktgCbwtG/assets/static/optimized/rev-164325c/wp-content/uploads/2020/02/Vegetarian-Curry-4381-Pinterest.jpg', 'This vegetarian Japanese curry is loaded with thick, meaty slices of king oyster mushrooms and colorful chunky vegetables such as kabocha, eggplant, and asparagus.', false, true, false)
;
